export const INIT_RECOMMEND = 'INIT_RECOMMEND';
export const INIT_PLAYLIST = 'INIT_PLAYLIST';
export const INIT_HOTSONGS = 'INIT_HOTSONGS';
export const INIT_HOTITEMS = 'INIT_HOTITEMS';
export const INPUT_SEARCH = 'INPUT_SEARCH';
export const COMMIT_SEARCH = 'COMMIT_SEARCH';
export const INIT_HISTORY = 'INIT_HISTORY';
export const DELETE_HISTORY = 'DELETE_HISTORY';